flush ruleset

table inet filter {
  set blocklist_v4 {
    type ipv4_addr
    flags interval, timeout
  }

  set ratelimit_v4 {
    type ipv4_addr
    flags interval, timeout
  }

  set watchlist_v4 {
    type ipv4_addr
    flags interval, timeout
  }

  chain input {
    type filter hook input priority 0; policy accept;

    ct state established,related accept
    iif "lo" accept
    tcp dport 22 accept

    ip saddr @blocklist_v4 counter drop

    ip saddr @ratelimit_v4 limit rate 30/second burst 60 packets counter accept
    ip saddr @ratelimit_v4 counter drop

    ip saddr @watchlist_v4 limit rate 5/second burst 10 packets counter log prefix "MB_WATCH"
  }

  chain forward {
    type filter hook forward priority 0; policy accept;

    ip saddr @blocklist_v4 counter drop

    ip saddr @ratelimit_v4 limit rate 30/second burst 60 packets counter accept
    ip saddr @ratelimit_v4 counter drop

    ip saddr @watchlist_v4 limit rate 5/second burst 10 packets counter log prefix "MB_WATCH"
  }
}
